controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
# homepage:
#  path: /{name}
#  controller: App\Controller\IndexController::home
